import json
import re
from typing import Dict, Any, List

class ValidationError(Exception):
    """Exception raised when LLM output fails schema validation or JSON parsing."""
    pass

class StructuredOutputEnforcer:
    """
    Enforces consistent JSON output from any LLM agent by wrapping prompts
    and robustly parsing and validating the results.
    """

    def wrap_prompt(self, original_prompt: str) -> str:
        """
        Appends a strict JSON schema instruction to any existing prompt.

        Args:
            original_prompt (str): The initial prompt intended for the LLM.

        Returns:
            str: The modified prompt with strict JSON instructions.
        """
        schema_instruction = (
            "\n\n---\n"
            "IMPORTANT INSTRUCTION: You MUST format your entire response as a single, valid JSON object. "
            "Do not include any other text, explanations, or markdown formatting outside of the JSON block.\n"
            "The JSON object MUST strictly adhere to the following schema:\n"
            "{\n"
            '  "main_answer": "your detailed string answer here",\n'
            '  "key_findings": ["finding 1", "finding 2"],\n'
            '  "confidence": "HIGH", // MUST be exactly one of: HIGH, MEDIUM, LOW\n'
            '  "sources_used": ["source 1", "source 2"]\n'
            "}\n"
        )
        return original_prompt + schema_instruction

    def parse_output(self, raw_output: str) -> dict:
        """
        Robustly extracts the JSON dict from LLM output even if the model
        adds extra text, markdown fences, or whitespace around the JSON.

        Args:
            raw_output (str): The raw text output generated by the LLM.

        Returns:
            dict: The parsed and validated JSON dictionary.

        Raises:
            ValidationError: If no valid JSON is found, JSON parsing fails, or schema validation fails.
        """
        # Search for markdown code blocks containing JSON
        pattern = r"```(?:json)?\s*(.*?)\s*```"
        match = re.search(pattern, raw_output, re.DOTALL | re.IGNORECASE)
        extracted_text = match.group(1) if match else raw_output

        # Locate the first '{' and the last '}' to capture the JSON object
        start_idx = extracted_text.find('{')
        end_idx = extracted_text.rfind('}')

        if start_idx == -1 or end_idx == -1 or start_idx > end_idx:
            raise ValidationError("Could not find a valid JSON object starting with '{' and ending with '}'.")

        json_str = extracted_text[start_idx:end_idx + 1]

        try:
            parsed = json.loads(json_str)
        except json.JSONDecodeError as e:
            raise ValidationError(f"JSON decode error: {str(e)}. Attempted to parse: {json_str}")

        if not isinstance(parsed, dict):
            raise ValidationError(f"Expected a JSON object (dictionary), but got {type(parsed).__name__}.")

        # Validate parsed JSON against the required schema
        self.validate_schema(parsed)

        return parsed

    def validate_schema(self, parsed: dict) -> bool:
        """
        Validates the parsed JSON dictionary against the required schema constraints.

        Args:
            parsed (dict): The dictionary to validate.

        Returns:
            bool: True only if all required keys are present, have the correct type, and are non-empty.

        Raises:
            ValidationError: With a full error message explaining exactly what key was missing or invalid.
        """
        required_schema = {
            "main_answer": str,
            "key_findings": list,
            "confidence": str,
            "sources_used": list
        }

        # 1. Check for required keys and basic types/emptiness
        for key, expected_type in required_schema.items():
            if key not in parsed:
                raise ValidationError(f"Schema Validation Failed: Missing required key '{key}'.")

            value = parsed[key]

            if not isinstance(value, expected_type):
                raise ValidationError(f"Schema Validation Failed: Key '{key}' must be of type {expected_type.__name__}, got {type(value).__name__}.")

            if expected_type == str and not value.strip():
                raise ValidationError(f"Schema Validation Failed: Key '{key}' cannot be an empty string.")

            if expected_type == list and len(value) == 0:
                raise ValidationError(f"Schema Validation Failed: Key '{key}' cannot be an empty list.")

        # 2. Validate specific constrained values
        confidence = parsed.get("confidence")
        allowed_confidences = {"HIGH", "MEDIUM", "LOW"}
        if confidence not in allowed_confidences:
            raise ValidationError(f"Schema Validation Failed: 'confidence' must be one of {allowed_confidences}. Got '{confidence}'.")

        # 3. Validate elements inside required lists
        for i, finding in enumerate(parsed.get("key_findings", [])):
            if not isinstance(finding, str) or not finding.strip():
                raise ValidationError(f"Schema Validation Failed: Element at index {i} in 'key_findings' is not a valid non-empty string.")

        for i, source in enumerate(parsed.get("sources_used", [])):
            if not isinstance(source, str) or not source.strip():
                raise ValidationError(f"Schema Validation Failed: Element at index {i} in 'sources_used' is not a valid non-empty string.")

        return True
